#include <iostream>

int main() {
    int answer;
    std::cout << "What is 1 + 1? ";
    std::cin >> answer;

    if (answer == 2) {
        std::cout << "You are correct!" << std::endl;
    } else {
        std::cout << "Sorry, that's not correct." << std::endl;
    }

    // Wait for the user to press Enter before closing
    std::cout << "Press Enter to exit...";
    std::cin.ignore(); // Ignore the newline left in the buffer
    std::cin.get(); // Wait for the user to press Enter

    return 0;
}
int main() {
    visionTest();
    return 0;
}
